#!/bin/bash
set -eou pipefail

source="${BASH_SOURCE[0]:-${(%):-%x}}"
command_chain+="$(basename "$source")"

usage() {
  cat <<EOF
Gokite buildkite is a tool for managing your Go Buildkite pipelines.

Usage:

   $command_chain <command> [arguments]

The commands are:

$(cmds "$source" | while read -r line; do echo -e "   ${line}"; done)

EOF
  exit 1
}

[[ $# -lt 1 ]] && usage

action="${1:-}"
module="$(cmd "$source" "$action")"
echo "$module" >&2
test -x "$module" || usage

shift
source "$module"
